name: 'Check for changes to a PR'
description: 'Check for changes and comment on PR if there are any'
inputs:
  token:
    description: 'The GitHub token to use.  You probably just want to use {{ secrets.GITHUB_TOKEN }}.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run apply
      uses: getsyncer/action-syncer/apply@main # TODO: I wish I could just do "uses: ../apply" can someone figure out how to make that work
    - name: check for changes
      id: changes
      shell: bash
      run: |
        if [[ `git diff --exit-code` ]]; then
          echo "CHANGES=true" >> "$GITHUB_OUTPUT"
          echo 'Files causing linting to fail:'
          git diff --name-only
        else
          echo "CHANGES=false" >> "$GITHUB_OUTPUT"
        fi
    - name: 'Comment PR on changes'
      uses: actions/github-script@v7.0.1
      if: steps.changes.outputs.CHANGES == 'true' && github.event_name == 'pull_request'
      with:
        github-token: ${{ inputs.token }}
        script: |
          const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
          github.rest.issues.createComment({ issue_number, owner, repo, body: 'Syncer files are changed.  Try commenting /sync to auto push a resync' });
    - name: Fail job
      if: steps.changes.outputs.CHANGES == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          core.setFailed('syncer changes detected')