name: 'Execute syncer plan'
description: 'Run plan and exit with code 1 if there are any changes'

runs:
  using: "composite"
  steps:
    - name: Install syncer
      uses: getsyncer/action-syncer/install@main # TODO: I wish I could just do "uses: ../install" can someone figure out how to make that work
    - name: Run plan
      shell: bash
      run: |
          syncer plan --exit-code