name: 'Execute syncer apply'
description: 'Run apply'

runs:
  using: "composite"
  steps:
    - name: Install syncer
      uses: getsyncer/action-syncer/install@main # TODO: I wish I could just do "uses: ../install" can someone figure out how to make that work
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        ## limits ssh access and adds the ssh public key for the user which triggered the workflow
        limit-access-to-actor: true
        ## limits ssh access and adds the ssh public keys of the listed GitHub users
        limit-access-to-users: cep21
    - name: Run apply
      shell: bash
      run: |
          pwd
          ls -la
          ls -la getsyncer
          LOG_LEVEL=debug syncer apply
