name: 'Install syncer application'
description: 'Just install syncer'

runs:
  using: "composite"
  steps:
    - name: setup go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20
    # TODO: Download pre compiled version
    - name: Install syncer
      shell: bash
      run: |
        cd "$TMPCHECKOUT"
        git clone https://github.com/cresta/syncer.git
        cd syncer
        go install ./cmd/syncer
        which syncer
        cd ..
        rm -rf syncer
      env:
        TMPCHECKOUT: ${{ runner.temp }}