name: 'Install syncer application'
description: 'Just install syncer'
inputs:
  version:
    description: 'Version to install.  Defaults to latest'
    required: false
    default: "v0.0.12"

runs:
  using: "composite"
  steps:
    - name: Setup bin path
      id: binpath
      shell: bash
      run: |
        mkdir -p "$BIN_DIR"
        echo "$BIN_DIR" >> $GITHUB_PATH
        echo "bin-dir=$BIN_DIR" >> $GITHUB_OUTPUT
      env:
        BIN_DIR: ${{ runner.temp }}/${{ github.run_id }}/syncer/bin
    - name: Install syncer
      shell: bash
      run: |
        # TODO: Use tools cache by first downloading the file to the tools cache and checking there
        # TODO: Use correct arch rather than assume Linux and x86_64
        curl --silent --fail --location --output "$TEMPDIR/syncer" https://github.com/getsyncer/syncer/releases/download/${{ inputs.version}}/syncer_Linux_x86_64.tar.gz
        tar -xzf $TEMPDIR/syncer -C $TEMPDIR
        mv $TEMPDIR/syncer "$BIN_DIR/syncer"
      env:
        BIN_DIR: ${{ steps.binpath.outputs.bin-dir }}
        TEMPDIR: ${{ runner.temp }}
