name: 'Install syncer application'
description: 'Just install syncer'
inputs:
  version:
    description: 'Version to install.  Defaults to latest'
    required: false
    default: "v0.0.1"

runs:
  using: "composite"
  steps:
    - name: Setup bin path
      id: binpath
      shell: bash
      run: |
        mkdir -p "$BIN_DIR"
        echo "$BIN_DIR" >> $GITHUB_PATH
        echo "bin-dir=$BIN_DIR" >> $GITHUB_OUTPUT
      env:
        BIN_DIR: ${{ runner.temp }}/${{ github.run_id }}/syncer/bin
    - name: Install syncer
      shell: bash
      run: |
        # TODO: Use tools cache
        curl --silent --fail --location --output /tmp/syncer https://github.com/cresta/syncer/releases/download/${{ inputs.version}}/syncer_Linux_x86_64.tar.gz
        tar -xzf /tmp/syncer -C /tmp
        mv /tmp/syncer "$BIN_DIR/syncer"
      env:
        BIN_DIR: ${{ steps.binpath.outputs.BIN_DIR }}